### ISSUE TITLE
Find actions does not work

### ISSUE THREAD

**Issue by Tsourdox** [aljazerzen/mongodb-typescript#14]
I've tried implementing the code under "Quick Start" guide and I get till error whenever I try to retreive anything from the database.

`TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined`

Inserting works fine, any thoughts on why you quick start example ain't working?

**Comment by Tsourdox** [comment]
So I think this should be added to your docs:
`emitDecoratorMetadata and experimentalDecorators must be enabled in tsconfig.json`

I only had experimentalDecorators enabled.

**Comment by aljazerzen** [comment]
Oh, thanks for noticing. 

Will add to the documentation.
