### ISSUE TITLE
Bump class-transformer vesion to 0.2.1

### ISSUE THREAD

**Issue by prohumine** [aljazerzen/mongodb-typescript#16]
Hi, I really like the project. I have a use case where I need to have a buffer in mongo, as I was trying to implement it I ran into the issue that version 0.1.9 and 0.1.10 of class-transformer does not support buffer types in Classes. But they have since fixed it in 0.2.1. I was hoping for a version bump to at least 0.2.1 if not to latest(0.2.3) to support buffers.

Implementation of library is still the same: `const realUsers = plainToClass(User, user);`

**Comment by aljazerzen** [comment]
Yeah, should be doable. Can do it and open a PR, or should I?

(also, do happen to know how to set automatic subscription to all new issues of my repository?)

**Comment by aljazerzen** [comment]
Done with #18
