### ISSUE TITLE
Make db as parameter (as collection)?!

### ISSUE THREAD

**Issue by colorcube** [aljazerzen/mongodb-typescript#2]
I'm fairly new to mongodb so this might not a real problem ...

With a `mongodb://.../mydb` url you can also define the db. I guess that's how you should use Repository().
As I understand mongo will use that db also for authentication which will not work for my use case.
So what I normally do is `mongo.db('mydb')`

Unfortunately this is not possible with Repository. Extending the class doesn't work because you have to call super().

```
export class Repository<T> {
  constructor(protected Type: ClassType<T>, mongo: MongoClient, collection: string, options?: RepositoryOptions) {
this.collection = mongo.db().collection(collection);
```

PS: really nice project
exactly what I was looking for

**Comment by aljazerzen** [comment]
True, the `Repository` does not have such option and would need one.

I have implemented this in commit 54a57f6f08b8482e21570f40626a214a611ee621.

I hope it helps even though a bit late...
